# Generated by Django 5.1.6 on 2025-02-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partner_company_alter_partner_participation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={},
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='company',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='participation',
        ),
        migrations.AddField(
            model_name='partner',
            name='cpf',
            field=models.CharField(default=1, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='partner',
            table=None,
        ),
    ]
