# Generated by Django 5.1.6 on 2025-02-25 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_partner_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partner')),
            ],
            options={
                'unique_together': {('partner', 'company')},
            },
        ),
    ]
